export const CalendarEventEnum = {
  REGISTRATION: 'REGISTRATION',
  ENROLLMENT: 'ENROLLMENT',
  ORIENTATION: 'ORIENTATION',
  START_OF_CLASSES: 'START_OF_CLASSES',
  HOLIDAY: 'HOLIDAY',
  UNIVERSITY_EVENT: 'UNIVERSITY_EVENT',
  DEADLINE: 'DEADLINE',
  PERIODIC_EXAM: 'PERIODIC_EXAM',
  END_OF_CLASSES: 'END_OF_CLASSES',
  GRADE_SUBMISSION: 'GRADE_SUBMISSION',
  GRADUATION: 'GRADUATION',
  FACULTY_EVALUATION: 'FACULTY_EVALUATION',
  ACADEMIC_TRANSITION: 'ACADEMIC_TRANSITION',
  OTHER: 'OTHER',
} as const;

export type CalendarEventEnum = (typeof CalendarEventEnum)[keyof typeof CalendarEventEnum];
