version: '3.8'

services:
  # React TypeScript App
  frontend:
    build:
      context: ./app
      dockerfile: ../docker/app/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules # exclude node_modules from host mount
      - ./app:/app:cached # cached improves macOS/Windows perf
    environment:
      - REACT_APP_API_URL=http://backend:8000 # use service name, not localhost
    depends_on:
      - backend

  # Laravel API
  backend:
    build:
      context: ./api
      dockerfile: ../docker/api/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./api:/var/www/html:cached
      - ./api/public:/var/www/html/public
      - laravel_storage:/var/www/html/storage
      - /var/www/html/bootstrap/cache
      - /var/www/html/vendor
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=edusync
      - DB_USERNAME=edusync
      - DB_PASSWORD=password
    depends_on:
      - mysql

  # MySQL Database
  mysql:
    container_name: edusync-mysql
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=edusync
      - MYSQL_USER=edusync
      - MYSQL_PASSWORD=password
    command: >
      --innodb-buffer-pool-size=512M
      --slow-query-log=1
      --long-query-time=2
      --innodb-log-file-size=128M
      --innodb-flush-log-at-trx-commit=2
      --log-bin-trust-function-creators=1
    volumes:
      - mysql_data:/var/lib/mysql

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - mysql

volumes:
  mysql_data:
  laravel_storage:
