version: '3.8'

services:
  # React TypeScript App
  frontend:
    build:
      context: ./app
      dockerfile: ../docker/app/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app:cached # cached improves macOS/Windows perf
      - /app/node_modules # exclude node_modules from host mount
      - /app/dist # exclude Vite build output
      - /app/.vite # exclude Vite cache
      - /app/.cache # exclude various cache directories
      - /app/coverage # exclude test coverage reports
      - /app/.nyc_output # exclude NYC coverage output
      - /app/.eslintcache # exclude ESLint cache
      - /app/.turbo # exclude Turbo cache
      - /app/.yarn/cache # exclude Yarn cache
      - /app/.pnpm-store # exclude PNPM store
    environment:
      - REACT_APP_API_URL=http://backend:8000 # use service name, not localhost
    depends_on:
      - backend

  # Laravel API
  backend:
    build:
      context: ./api
      dockerfile: ../docker/api/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./api:/var/www/html:cached
      - ./api/storage:/var/www/html/storage
      - ./api/public:/var/www/html/public
      - laravel_storage:/var/www/html/storage
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=cpanel
      - DB_USERNAME=cpanel
      - DB_PASSWORD=password
    depends_on:
      - mysql

  # MySQL Database
  mysql:
    container_name: cpanel-mysql
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cpanel
      - MYSQL_USER=cpanel
      - MYSQL_PASSWORD=password
    command: >
      --innodb-buffer-pool-size=512M
      --slow-query-log=1
      --long-query-time=2
      --innodb-log-file-size=128M
      --innodb-flush-log-at-trx-commit=2
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  laravel_storage:
