/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { AcademicCalendarEvent } from './academicCalendarEvent';
import type { SchoolYear } from './schoolYear';

export interface AcademicCalendar {
  readonly id?: number;
  name?: string;
  /** @nullable */
  description?: string | null;
  start_date?: string;
  end_date?: string;
  school_year_id?: number;
  event?: AcademicCalendarEvent;
  readonly created_at?: string;
  readonly updated_at?: string;
  school_year?: SchoolYear;
}
