/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { AcademicProgram } from './academicProgram';
import type { SchoolYear } from './schoolYear';

export interface AcademicProgramCriteria {
  id?: number;
  academic_program_id: number;
  school_year_id: number;
  title: string;
  /** @nullable */
  description?: string | null;
  max_score: number;
  min_score: number;
  weight: number;
  is_active: boolean;
  created_at?: string;
  updated_at?: string;
  academic_program?: AcademicProgram;
  school_year?: SchoolYear;
}
