/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { College } from './college';
import type { ProgramType } from './programType';

export interface AcademicProgram {
  id?: number;
  program_name: string;
  short_name: string;
  year_first_implemented: string;
  college_id: number;
  program_type_id: number;
  created_at?: string;
  updated_at?: string;
  college?: College;
  program_type?: ProgramType;
}
