/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { AcademicProgram } from './academicProgram';
import type { Requirement } from './requirement';
import type { SchoolYear } from './schoolYear';

export interface AcademicProgramRequirement {
  readonly id?: number;
  academic_program_id: number;
  requirement_id: number;
  school_year_id: number;
  is_mandatory: boolean;
  is_active: boolean;
  readonly created_at?: string;
  readonly updated_at?: string;
  academic_program?: AcademicProgram;
  requirement?: Requirement;
  school_year?: SchoolYear;
}
