/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type AcademicCalendarEvent = typeof AcademicCalendarEvent[keyof typeof AcademicCalendarEvent];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AcademicCalendarEvent = {
  REGISTRATION: 'REGISTRATION',
  ENROLLMENT: 'ENROLLMENT',
  ORIENTATION: 'ORIENTATION',
  START_OF_CLASSES: 'START_OF_CLASSES',
  ACADEMIC_TRANSITION: 'ACADEMIC_TRANSITION',
  PERIODIC_EXAM: 'PERIODIC_EXAM',
  END_OF_CLASSES: 'END_OF_CLASSES',
  FACULTY_EVALUATION: 'FACULTY_EVALUATION',
  GRADE_SUBMISSION: 'GRADE_SUBMISSION',
  DEADLINE: 'DEADLINE',
  GRADUATION: 'GRADUATION',
  UNIVERSITY_EVENT: 'UNIVERSITY_EVENT',
  HOLIDAY: 'HOLIDAY',
  OTHER: 'OTHER',
} as const;
