/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export interface AcademicTerm {
  id?: number;
  name: string;
  /** @nullable */
  description: string | null;
  suffix: string;
  number_of_terms: number;
  readonly created_at?: string;
  readonly updated_at?: string;
}
