/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type AdmissionApplicationLogType = typeof AdmissionApplicationLogType[keyof typeof AdmissionApplicationLogType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdmissionApplicationLogType = {
  submitted: 'submitted',
  cancelled: 'cancelled',
  approved: 'approved',
  rejected: 'rejected',
} as const;
