/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { AdmissionApplication } from './admissionApplication';
import type { AdmissionCriteria } from './admissionCriteria';
import type { User } from './user';

export interface AdmissionApplicationScore {
  readonly id?: number;
  admission_application_id: number;
  admission_criteria_id: number;
  user_id: number;
  score: number;
  /** @nullable */
  comments?: string | null;
  is_posted: boolean;
  created_at?: string;
  updated_at?: string;
  admission_application?: AdmissionApplication;
  admission_criteria?: AdmissionCriteria;
  user?: User;
}
