/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { AdmissionApplicationLogType } from './admissionApplicationLogType';
import type { AdmissionApplication } from './admissionApplication';
import type { User } from './user';

export interface AdmissionApplicationLog {
  readonly id?: number;
  admission_application_id: number;
  user_id: number;
  type: AdmissionApplicationLogType;
  /** @nullable */
  note?: string | null;
  created_at?: string;
  updated_at?: string;
  admissionApplication?: AdmissionApplication;
  user?: User;
}
