/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { UniversityAdmission } from './universityAdmission';
import type { AcademicProgram } from './academicProgram';
import type { AdmissionCriteria } from './admissionCriteria';

export interface AdmissionSchedule {
  readonly id?: number;
  university_admission_id: number;
  academic_program_id: number;
  title?: string;
  intake_limit: number;
  start_date: string;
  end_date: string;
  readonly created_at?: string;
  readonly updated_at?: string;
  university_admission?: UniversityAdmission;
  academic_program?: AcademicProgram;
  admission_criterias?: AdmissionCriteria[];
}
