/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { AdmissionApplicationLatestStatus } from './admissionApplicationLatestStatus';
import type { User } from './user';
import type { AdmissionSchedule } from './admissionSchedule';
import type { AdmissionApplicationLog } from './admissionApplicationLog';

export interface AdmissionApplication {
  readonly id?: number;
  user_id: number;
  admission_schedule_id: number;
  first_name: string;
  last_name: string;
  /** @nullable */
  middle_name?: string | null;
  email: string;
  phone: string;
  address: string;
  created_at?: string;
  updated_at?: string;
  readonly latest_status?: AdmissionApplicationLatestStatus;
  readonly latest_status_label?: string;
  is_open_for_enrollment?: boolean;
  user?: User;
  admission_schedule?: AdmissionSchedule;
  logs?: AdmissionApplicationLog[];
}
