/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { SchoolYear } from './schoolYear';
import type { Campus } from './campus';

export interface AdmissionSchedule {
  readonly id?: number;
  school_year_id: number;
  campus_id: number;
  start_date: string;
  end_date: string;
  readonly created_at?: string;
  readonly updated_at?: string;
  school_year?: SchoolYear;
  campus?: Campus;
}
