/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { AcademicProgram } from './academicProgram';
import type { AdmissionSchedule } from './admissionSchedule';
import type { Requirement } from './requirement';

export interface AdmissionCriteria {
  id?: number;
  academic_program_id: number;
  admission_schedule_id: number;
  requirement_id: number;
  title: string;
  /** @nullable */
  description?: string | null;
  max_score: number;
  min_score: number;
  weight: number;
  is_active: boolean;
  file_suffix: string;
  created_at?: string;
  updated_at?: string;
  academic_program?: AcademicProgram;
  admission_schedule?: AdmissionSchedule;
  requirement?: Requirement;
}
