/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export interface AdmissionApplication {
  year?: number;
  pool_no?: number;
  firstName: string;
  lastName: string;
  /** @nullable */
  middleName?: string | null;
  email: string;
  phone: string;
  address: string;
  created_at?: string;
  updated_at?: string;
}
