/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { AdmissionApplication } from './admissionApplication';
import type { AcademicProgramCriteria } from './academicProgramCriteria';

export interface AdmissionScore {
  readonly id?: number;
  admission_application_id: number;
  academic_program_criteria_id: number;
  score: number;
  /** @nullable */
  comments?: string | null;
  is_passed: boolean;
  created_at?: string;
  updated_at?: string;
  admissionApplication?: AdmissionApplication;
  academicProgramCriteria?: AcademicProgramCriteria;
}
