/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';
import type { SchoolYear } from './schoolYear';
import type { AcademicProgram } from './academicProgram';
import type { AdmissionApplicationLog } from './admissionApplicationLog';

export interface AdmissionApplication {
  readonly id?: number;
  user_id: number;
  school_year_id: number;
  academic_program_id: number;
  year?: number;
  pool_no?: number;
  first_name: string;
  last_name: string;
  /** @nullable */
  middle_name?: string | null;
  email: string;
  phone: string;
  address: string;
  created_at?: string;
  updated_at?: string;
  latest_status?: string;
  is_open_for_enrollment?: boolean;
  user?: User;
  school_year?: SchoolYear;
  academic_program?: AcademicProgram;
  logs?: AdmissionApplicationLog[];
}
