/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { SchoolYear } from './schoolYear';
import type { AcademicProgram } from './academicProgram';

export interface AdmissionSchedule {
  readonly id?: number;
  school_year_id: number;
  academic_program_id: number;
  intake_limit: number;
  start_date: string;
  end_date: string;
  readonly created_at?: string;
  readonly updated_at?: string;
  school_year?: SchoolYear;
  academic_program?: AcademicProgram;
}
