/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export interface Building {
  id?: number;
  /** @maxLength 50 */
  name: string;
  /** @maxLength 25 */
  short_name: string;
  latitude: number;
  longitude: number;
  campus_id: number;
  created_at?: string;
  updated_at?: string;
}
