/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export interface Campus {
  id?: number;
  name: string;
  short_name: string;
  address: string;
  main_campus: boolean;
}
