/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export interface College {
  id?: number;
  college_name: string;
  college_shortname: string;
  campus_id: number;
  created_at?: string;
  updated_at?: string;
}
