/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { CourseRequisiteTypeEnum } from './courseRequisiteTypeEnum';
import type { Course } from './course';

export interface CourseRequisite {
  id?: number;
  course_id: number;
  requisite_course_id: number;
  requisite_type: CourseRequisiteTypeEnum;
  created_at?: string;
  updated_at?: string;
  requisite_course?: Course;
}
