/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type CourseRequisiteRequisiteType = typeof CourseRequisiteRequisiteType[keyof typeof CourseRequisiteRequisiteType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CourseRequisiteRequisiteType = {
  co: 'co',
  pre: 'pre',
  equivalent: 'equivalent',
} as const;
