/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type CourseRequisiteTypeEnum = typeof CourseRequisiteTypeEnum[keyof typeof CourseRequisiteTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CourseRequisiteTypeEnum = {
  co: 'co',
  pre: 'pre',
  equivalent: 'equivalent',
} as const;
