/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export interface Course {
  id?: number;
  course_code: string;
  course_title: string;
  course_description: string;
  with_laboratory: boolean;
  is_specialize: boolean;
  lecture_units: number;
  laboratory_units: number;
  credit_units: number;
  created_at?: string;
  updated_at?: string;
}
