/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { AcademicProgram } from './academicProgram';

export interface CreateAcademicProgramResponse200 {
  success?: boolean;
  data?: AcademicProgram;
}
