/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type CurriculumStateEnum = typeof CurriculumStateEnum[keyof typeof CurriculumStateEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CurriculumStateEnum = {
  active: 'active',
  inactive: 'inactive',
  archived: 'archived',
} as const;
