/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { CurriculumStatus } from './curriculumStatus';

export interface Curriculum {
  id?: number;
  academic_program_id: number;
  curriculum_code: string;
  curriculum_name: string;
  /** @nullable */
  description: string | null;
  effective_year: number;
  total_units: number;
  total_hours: number;
  status: CurriculumStatus;
  /** @nullable */
  approved_date: string | null;
  created_at?: string;
  updated_at?: string;
}
