/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { CurriculumStatus } from './curriculumStatus';
import type { SchoolYear } from './schoolYear';
import type { AcademicProgram } from './academicProgram';
import type { AcademicTerm } from './academicTerm';

export interface Curriculum {
  id?: number;
  school_year_id?: number;
  academic_program_id: number;
  academic_term_id: number;
  curriculum_code: string;
  curriculum_name: string;
  /** @nullable */
  description: string | null;
  effective_year: number;
  total_units: number;
  total_hours: number;
  readonly status: CurriculumStatus;
  /** @nullable */
  approved_date: string | null;
  created_at?: string;
  updated_at?: string;
  school_year?: SchoolYear;
  academic_program?: AcademicProgram;
  academic_term?: AcademicTerm;
}
