/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type CurriculumStatus = typeof CurriculumStatus[keyof typeof CurriculumStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CurriculumStatus = {
  active: 'active',
  inactive: 'inactive',
  archived: 'archived',
} as const;
