/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { Curriculum } from './curriculum';
import type { User } from './user';

export interface CurriculumTagging {
  id?: number;
  curriculum_id: number;
  user_id: number;
  is_active: boolean;
  created_at?: string;
  updated_at?: string;
  is_internal_student?: boolean;
  curriculum?: Curriculum;
  user?: User;
}
