/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { Curriculum } from './curriculum';
import type { Course } from './course';

export interface CurriculumDetail {
  id?: number;
  curriculum_id: number;
  course_id: number;
  year_order: number;
  term_order: number;
  term_alias: string;
  is_include_gwa: boolean;
  readonly created_at?: string;
  readonly updated_at?: string;
  curriculum?: Curriculum;
  course?: Course;
  readonly year_label?: string;
  readonly term_label?: string;
}
