/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export interface Designition {
  id?: number;
  user_id: number;
  is_active: boolean;
  designitionable_id: number;
  designitionable_type: string;
  created_at?: string;
  updated_at?: string;
}
