/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export interface DocumentType {
  id?: number;
  document_type_name: string;
  description: string;
  price: number;
  created_at?: string;
  updated_at?: string;
}
