/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type DocumentRequestLogAction = typeof DocumentRequestLogAction[keyof typeof DocumentRequestLogAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DocumentRequestLogAction = {
  submitted: 'submitted',
  cancelled: 'cancelled',
  paid: 'paid',
  rejected: 'rejected',
  processing: 'processing',
  pickup: 'pickup',
  completed: 'completed',
} as const;
