/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentRequestLogActionEnum } from './documentRequestLogActionEnum';
import type { DocumentRequest } from './documentRequest';
import type { User } from './user';

export interface DocumentRequestLog {
  id?: number;
  document_request_id: number;
  user_id: number;
  action: DocumentRequestLogActionEnum;
  note: string;
  created_at?: string;
  updated_at?: string;
  document_request?: DocumentRequest;
  user?: User;
}
