/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentRequestLatestStatus } from './documentRequestLatestStatus';
import type { DocumentRequestLog } from './documentRequestLog';
import type { User } from './user';
import type { Campus } from './campus';
import type { DocumentType } from './documentType';

export interface DocumentRequest {
  id?: number;
  user_id: number;
  campus_id: number;
  document_type_id: number;
  purpose: string;
  created_at?: string;
  updated_at?: string;
  readonly latest_status?: DocumentRequestLatestStatus;
  readonly latest_status_label?: string;
  logs?: DocumentRequestLog[];
  readonly is_cancellable?: boolean;
  user?: User;
  campus?: Campus;
  document_type?: DocumentType;
}
