/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';
import type { Section } from './section';
import type { EnrollmentLog } from './enrollmentLog';

export interface Enrollment {
  readonly id?: number;
  user_id: number;
  section_id: number;
  readonly created_at?: string;
  readonly updated_at?: string;
  readonly validated?: boolean;
  user?: User;
  section?: Section;
  enrollmentLogs?: EnrollmentLog[];
}
