/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { EnrollmentLogActionEnum } from './enrollmentLogActionEnum';
import type { Enrollment } from './enrollment';
import type { User } from './user';

export interface EnrollmentLog {
  readonly id?: number;
  enrollment_id: number;
  user_id: number;
  action: EnrollmentLogActionEnum;
  /** @nullable */
  note?: string | null;
  readonly created_at?: string;
  readonly updated_at?: string;
  enrollment?: Enrollment;
  user?: User;
}
