/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type EnrollmentLatestStatus = typeof EnrollmentLatestStatus[keyof typeof EnrollmentLatestStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnrollmentLatestStatus = {
  enroll: 'enroll',
  program_chair_approved: 'program_chair_approved',
  registrar_approved: 'registrar_approved',
  program_chair_dropped_approved: 'program_chair_dropped_approved',
  registrar_dropped_approved: 'registrar_dropped_approved',
  dropped: 'dropped',
  rejected: 'rejected',
} as const;
