/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type EnrollmentLogAction = typeof EnrollmentLogAction[keyof typeof EnrollmentLogAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnrollmentLogAction = {
  enroll: 'enroll',
  program_chair_approved: 'program_chair_approved',
  registrar_approved: 'registrar_approved',
  program_chair_dropped_approved: 'program_chair_dropped_approved',
  registrar_dropped_approved: 'registrar_dropped_approved',
  dropped: 'dropped',
} as const;
