/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { FamilyBackgroundRelationship } from './familyBackgroundRelationship';

export interface FamilyBackground {
  id?: number;
  user_id: number;
  fullname: string;
  relationship: FamilyBackgroundRelationship;
  /** @nullable */
  occupation?: string | null;
  /** @nullable */
  birthdate?: string | null;
  created_at?: string;
  updated_at?: string;
}
