/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type FamilyBackgroundRelationship = typeof FamilyBackgroundRelationship[keyof typeof FamilyBackgroundRelationship];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FamilyBackgroundRelationship = {
  father: 'father',
  mother: 'mother',
  brother: 'brother',
  guardian: 'guardian',
  other: 'other',
} as const;
