/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type FamilyRelationshipTypeEnum = typeof FamilyRelationshipTypeEnum[keyof typeof FamilyRelationshipTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FamilyRelationshipTypeEnum = {
  father: 'father',
  mother: 'mother',
  brother: 'brother',
  guardian: 'guardian',
  other: 'other',
} as const;
