/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { Enrollment } from './enrollment';

export interface FinalGrade {
  readonly id?: number;
  enrollment_id: number;
  grade: number;
  credited_units: number;
  is_posted: boolean;
  readonly created_at?: string;
  readonly updated_at?: string;
  enrollment?: Enrollment;
}
