/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export interface GenerateSection {
  curriculum_id?: number;
  year_order?: number;
  term_order?: number;
  auto_post?: boolean;
  number_of_section?: number;
}
