/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type GetAcademicProgramPaginatedParams = {
/**
 * Search term
 */
search?: string;
/**
 * Page number
 */
page?: number;
/**
 * Number of items per page
 */
rows?: number;
/**
 * Filter by college ID
 */
'filter[college_id]'?: number;
/**
 * Include program type
 */
include?: string;
};
