/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { AdmissionSchedule } from './admissionSchedule';

export interface GetAdmissionSchedulesResponse200 {
  success?: boolean;
  data?: AdmissionSchedule[];
}
