/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type GetAdmissionApplicationPaginatedParams = {
/**
 * Search term
 */
search?: string;
/**
 * Page number
 */
page?: number;
/**
 * Number of items per page
 */
rows?: number;
/**
 * User ID
 */
'filter[user_id]'?: number;
/**
 * School Year ID
 */
'filter[school_year_id]'?: number;
/**
 * Academic Program ID
 */
'filter[academic_program_id]'?: number;
};
