/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type GetAdmissionApplicationPaginatedFilterAcademicProgramIdSchoolYearIdLatestStatusLatestStatus = typeof GetAdmissionApplicationPaginatedFilterAcademicProgramIdSchoolYearIdLatestStatusLatestStatus[keyof typeof GetAdmissionApplicationPaginatedFilterAcademicProgramIdSchoolYearIdLatestStatusLatestStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAdmissionApplicationPaginatedFilterAcademicProgramIdSchoolYearIdLatestStatusLatestStatus = {
  submitted: 'submitted',
  cancelled: 'cancelled',
  approved: 'approved',
  rejected: 'rejected',
  accepted: 'accepted',
} as const;
