/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type GetAdmissionApplicationPaginatedParams = {
/**
 * Search term
 */
search?: string;
/**
 * Page number
 */
page?: number;
/**
 * Number of items per page
 */
rows?: number;
/**
 * Name
 */
'filter[name]'?: string;
/**
 * Latest Status
 */
'filter[latest_status]'?: string;
/**
 * User ID
 */
'filter[user_id]'?: number;
/**
 * Admission Schedule ID
 */
'filter[admission_schedule_id]'?: number;
/**
 * Academic Program ID
 */
'filter[academic_program_id]'?: number;
/**
 * Open Enrollment
 */
'filter[open_enrollment]'?: boolean;
};
