/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type GetAdmissionApplicationPaginatedFilterLatestStatus = typeof GetAdmissionApplicationPaginatedFilterLatestStatus[keyof typeof GetAdmissionApplicationPaginatedFilterLatestStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAdmissionApplicationPaginatedFilterLatestStatus = {
  submitted: 'submitted',
  cancelled: 'cancelled',
  approved: 'approved',
  rejected: 'rejected',
  accepted: 'accepted',
} as const;
