/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type GetAdmissionSchedulePaginatedParams = {
/**
 * Search term
 */
search?: string;
/**
 * Page number
 */
page?: number;
/**
 * Number of items per page
 */
rows?: number;
/**
 * Filter by college ID
 */
'filter[college_id]'?: number;
/**
 * Filter by academic program ID
 */
'filter[academic_program_id]'?: number;
/**
 * Filter by university admission ID
 */
'filter[university_admission_id]'?: number;
/**
 * Sort by start date and direction. Example: ?sort[start_date]=-start_date (descending), ?sort[start_date]=start_date (ascending)
 */
sort?: string;
};
