/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type GetActiveCampusesParams = {
/**
 * Filter by school year ID
 */
'filter[school_year_id]'?: number;
};
