/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type GetAdmissionCriteriaPaginatedParams = {
/**
 * Search term
 */
search?: string;
/**
 * Page number
 */
page?: number;
/**
 * Number of items per page
 */
rows?: number;
/**
 * Academic program ID
 */
'filter[academic_program_id]'?: number;
/**
 * Admission schedule ID
 */
'filter[admission_schedule_id]'?: number;
/**
 * Requirement ID
 */
'filter[requirement_id]'?: number;
};
