/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GetAcademicCalendarPaginatedFilterEvent } from './getAcademicCalendarPaginatedFilterEvent';

export type GetAcademicCalendarPaginatedParams = {
/**
 * Search term
 */
search?: string;
/**
 * Page number
 */
page?: number;
/**
 * Number of items per page
 */
rows?: number;
/**
 * Filter by school year ID
 */
'filter[school_year_id]'?: number;
/**
 * Filter by event
 */
'filter[event]'?: GetAcademicCalendarPaginatedFilterEvent;
/**
 * Comma-separated list of related resources to include in the response
 */
include?: string;
/**
 * Sort by order
 */
sort?: string;
};
