/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedCurriculumDetailResponse200 } from './paginatedCurriculumDetailResponse200';
import type { GetCurriculumDetailsResponse200 } from './getCurriculumDetailsResponse200';

export type GetCurriculumDetailPaginated200 = PaginatedCurriculumDetailResponse200 | GetCurriculumDetailsResponse200;
