/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedCurriculumResponse200 } from './paginatedCurriculumResponse200';
import type { GetCurriculumsResponse200 } from './getCurriculumsResponse200';

export type GetCurriculumPaginated200 = PaginatedCurriculumResponse200 | GetCurriculumsResponse200;
