/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type GetCurriculumTaggingPaginatedParams = {
/**
 * Search term
 */
search?: string;
/**
 * Page number
 */
page?: number;
/**
 * Number of items per page
 */
rows?: number;
/**
 * Filter by curriculum ID
 */
'filter[curriculum_id]'?: number;
/**
 * Filter by academic program ID
 */
'filter[academic_program_id]'?: number;
/**
 * Filter by college ID
 */
'filter[college_id]'?: number;
/**
 * Filter by campus ID
 */
'filter[campus_id]'?: number;
/**
 * Filter by search term
 */
'filter[search]'?: string;
};
