/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type GetDesignitionPaginatedFilterDesignitionableType = typeof GetDesignitionPaginatedFilterDesignitionableType[keyof typeof GetDesignitionPaginatedFilterDesignitionableType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetDesignitionPaginatedFilterDesignitionableType = {
  'App\Models\AcademicProgram': 'App\Models\AcademicProgram',
  'App\Models\College': 'App\Models\College',
  'App\Models\Campus': 'App\Models\Campus',
} as const;
