/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GetDesignitionPaginatedFilterDesignitionableType } from './getDesignitionPaginatedFilterDesignitionableType';

export type GetDesignitionPaginatedParams = {
/**
 * Search term
 */
search?: string;
/**
 * Page number
 */
page?: number;
/**
 * Number of items per page
 */
rows?: number;
/**
 * Filter by designitionable type
 */
'filter[designitionable_type]'?: GetDesignitionPaginatedFilterDesignitionableType;
};
