/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GetDocumentRequestPaginatedFilterLatestStatus } from './getDocumentRequestPaginatedFilterLatestStatus';

export type GetDocumentRequestPaginatedParams = {
/**
 * Search term
 */
search?: string;
/**
 * Page number
 */
page?: number;
/**
 * Number of items per page
 */
rows?: number;
/**
 * Filter by user ID
 */
'filter[user_id]'?: number;
/**
 * Filter by campus ID
 */
'filter[campus_id]'?: number;
/**
 * Filter by latest status
 */
'filter[latest_status]'?: GetDocumentRequestPaginatedFilterLatestStatus;
};
