/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GetEnrollmentsByCampusIdGroupedByUser200Data } from './getEnrollmentsByCampusIdGroupedByUser200Data';

export type GetEnrollmentsByCampusIdGroupedByUser200 = {
  status?: string;
  data?: GetEnrollmentsByCampusIdGroupedByUser200Data;
};
