/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GetEnrollmentsByCampusIdGroupedByUser200DataData } from './getEnrollmentsByCampusIdGroupedByUser200DataData';
import type { GetEnrollmentsByCampusIdGroupedByUser200DataLinksItem } from './getEnrollmentsByCampusIdGroupedByUser200DataLinksItem';

export type GetEnrollmentsByCampusIdGroupedByUser200Data = {
  current_page?: number;
  data?: GetEnrollmentsByCampusIdGroupedByUser200DataData;
  first_page_url?: string;
  from?: number;
  last_page?: number;
  last_page_url?: string;
  links?: GetEnrollmentsByCampusIdGroupedByUser200DataLinksItem[];
  /** @nullable */
  next_page_url?: string | null;
  path?: string;
  per_page?: number;
  /** @nullable */
  prev_page_url?: string | null;
  to?: number;
  total?: number;
};
