/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type GetEnrollmentsByCampusIdGroupedByUser200DataLinksItem = {
  /** @nullable */
  url?: string | null;
  label?: string;
  /** @nullable */
  page?: number | null;
  active?: boolean;
};
