/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type GetEnrollmentsByAcademicProgramIdGroupedByUserParams = {
/**
 * Page number
 */
page?: number;
/**
 * Number of items per page
 */
rows?: number;
/**
 * Latest status
 */
'filter[latest_status]'?: string;
/**
 * School year ID
 */
'filter[school_year_id]'?: number;
/**
 * Year ID
 */
'filter[year_id]'?: number;
/**
 * Term ID
 */
'filter[term_id]'?: number;
};
