/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type GetEnrollmentPaginatedParams = {
/**
 * Search term
 */
search?: string;
/**
 * Page number
 */
page?: number;
/**
 * Number of items per page
 */
rows?: number;
/**
 * User ID
 */
'filter[user_id]'?: number;
/**
 * Officially enrolled
 */
'filter[officially_enrolled]'?: boolean;
/**
 * Section ID
 */
'filter[section_id]'?: number;
};
