/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GetEnrollmentsByAcademicProgramIdGroupedByUser200DataData } from './getEnrollmentsByAcademicProgramIdGroupedByUser200DataData';
import type { GetEnrollmentsByAcademicProgramIdGroupedByUser200DataLinksItem } from './getEnrollmentsByAcademicProgramIdGroupedByUser200DataLinksItem';

export type GetEnrollmentsByAcademicProgramIdGroupedByUser200Data = {
  current_page?: number;
  data?: GetEnrollmentsByAcademicProgramIdGroupedByUser200DataData;
  first_page_url?: string;
  from?: number;
  last_page?: number;
  last_page_url?: string;
  links?: GetEnrollmentsByAcademicProgramIdGroupedByUser200DataLinksItem[];
  /** @nullable */
  next_page_url?: string | null;
  path?: string;
  per_page?: number;
  /** @nullable */
  prev_page_url?: string | null;
  to?: number;
  total?: number;
};
