/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GetSectionTeachersByProgramIdGroupedByTeacherName200DataData } from './getSectionTeachersByProgramIdGroupedByTeacherName200DataData';
import type { GetSectionTeachersByProgramIdGroupedByTeacherName200DataLinksItem } from './getSectionTeachersByProgramIdGroupedByTeacherName200DataLinksItem';

export type GetSectionTeachersByProgramIdGroupedByTeacherName200Data = {
  current_page?: number;
  data?: GetSectionTeachersByProgramIdGroupedByTeacherName200DataData;
  first_page_url?: string;
  from?: number;
  last_page?: number;
  last_page_url?: string;
  links?: GetSectionTeachersByProgramIdGroupedByTeacherName200DataLinksItem[];
  /** @nullable */
  next_page_url?: string | null;
  path?: string;
  per_page?: number;
  /** @nullable */
  prev_page_url?: string | null;
  to?: number;
  total?: number;
};
