/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GetSectionTeachersByCampusId200DataData } from './getSectionTeachersByCampusId200DataData';
import type { GetSectionTeachersByCampusId200DataLinksItem } from './getSectionTeachersByCampusId200DataLinksItem';

export type GetSectionTeachersByCampusId200Data = {
  current_page?: number;
  data?: GetSectionTeachersByCampusId200DataData;
  first_page_url?: string;
  from?: number;
  last_page?: number;
  last_page_url?: string;
  links?: GetSectionTeachersByCampusId200DataLinksItem[];
  /** @nullable */
  next_page_url?: string | null;
  path?: string;
  per_page?: number;
  /** @nullable */
  prev_page_url?: string | null;
  to?: number;
  total?: number;
};
