/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GetSectionTeachersByProgramIdGroupedByTeacherName200Data } from './getSectionTeachersByProgramIdGroupedByTeacherName200Data';

export type GetSectionTeachersByProgramIdGroupedByTeacherName200 = {
  status?: string;
  data?: GetSectionTeachersByProgramIdGroupedByTeacherName200Data;
};
