/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type GetSessionRolesItem = typeof GetSessionRolesItem[keyof typeof GetSessionRolesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetSessionRolesItem = {
  admin: 'admin',
  'program-chair': 'program-chair',
  'college-dean': 'college-dean',
  'specialization-chair': 'specialization-chair',
  'campus-scheduler': 'campus-scheduler',
  'campus-registrar': 'campus-registrar',
  student: 'student',
  faculty: 'faculty',
  guest: 'guest',
} as const;
