/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GetSessionRolesItem } from './getSessionRolesItem';

export interface GetSession {
  readonly id: number;
  readonly is_admin: boolean;
  readonly is_program_chair: boolean;
  readonly is_college_dean: boolean;
  readonly is_specialization_chair: boolean;
  readonly is_campus_scheduler: boolean;
  readonly is_campus_registrar: boolean;
  readonly is_student: boolean;
  readonly is_faculty: boolean;
  readonly is_guest: boolean;
  readonly roles?: readonly GetSessionRolesItem[];
  /** @nullable */
  readonly active_academic_program: number | null;
  /** @nullable */
  readonly active_college: number | null;
  /** @nullable */
  readonly active_specialization: number | null;
  /** @nullable */
  readonly active_campus: number | null;
  readonly profile_weight: number;
}
