/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type GetSchoolYearPaginatedParams = {
/**
 * Search term
 */
search?: string;
/**
 * Page number
 */
page?: number;
/**
 * Number of items per page
 */
rows?: number;
/**
 * Sort by fields and direction. Example: ?sort=-start_date (descending), ?sort=start_date (ascending). Supports multiple fields: ?sort=-start_date,title
 */
sort?: string;
};
