/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GetSessionRolesItem } from './getSessionRolesItem';

export interface GetSession {
  is_admin: boolean;
  is_program_chair: boolean;
  is_college_dean: boolean;
  is_specialization_chair: boolean;
  is_campus_scheduler: boolean;
  is_campus_registrar: boolean;
  is_student: boolean;
  is_faculty: boolean;
  is_guest: boolean;
  roles?: GetSessionRolesItem[];
  /** @nullable */
  active_academic_program: number | null;
  /** @nullable */
  active_college: number | null;
  /** @nullable */
  active_specialization: number | null;
  /** @nullable */
  active_campus: number | null;
}
