/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GetScholasticFilterByProgramId200Data } from './getScholasticFilterByProgramId200Data';

export type GetScholasticFilterByProgramId200 = {
  success?: boolean;
  data?: GetScholasticFilterByProgramId200Data;
};
