/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GetSectionTeachersByCampusId200Data } from './getSectionTeachersByCampusId200Data';

export type GetSectionTeachersByCampusId200 = {
  status?: string;
  data?: GetSectionTeachersByCampusId200Data;
};
