/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type GetSectionPaginatedParams = {
/**
 * Search term
 */
search?: string;
/**
 * Page number
 */
page?: number;
/**
 * Number of items per page
 */
rows?: number;
/**
 * Filter by curriculum ID
 */
'filter[curriculumDetail.curriculum_id]'?: number;
/**
 * Filter by school year ID
 */
'filter[school_year_id]'?: number;
/**
 * Filter by freshmen
 */
'filter[for_freshmen]'?: boolean;
/**
 * Paginate the results
 */
paginate?: boolean;
};
