/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GetScholasticFilterByCampusId200Data } from './getScholasticFilterByCampusId200Data';

export type GetScholasticFilterByCampusId200 = {
  success?: boolean;
  data?: GetScholasticFilterByCampusId200Data;
};
