/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type GetScholasticFilterByProgramIdParams = {
/**
 * Latest status
 */
'filter[latest_status]'?: string;
/**
 * School year ID
 */
'filter[school_year_id]'?: number;
};
