/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GetUniversityAdmissionApplicationPaginatedFilterLatestStatus } from './getUniversityAdmissionApplicationPaginatedFilterLatestStatus';

export type GetUniversityAdmissionApplicationPaginatedParams = {
/**
 * Search term
 */
search?: string;
/**
 * Page number
 */
page?: number;
/**
 * Number of items per page
 */
rows?: number;
/**
 * User ID
 */
'filter[user_id]'?: number;
/**
 * University admission ID
 */
'filter[university_admission_id]'?: number;
/**
 * University admission schedule ID
 */
'filter[university_admission_schedule_id]'?: number;
/**
 * Latest status
 */
'filter[latest_status]'?: GetUniversityAdmissionApplicationPaginatedFilterLatestStatus;
};
