/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GradeBookGradingPeriod } from './gradeBookGradingPeriod';
import type { GradeBookItemDetail } from './gradeBookItemDetail';

export interface GradeBookItem {
  readonly id?: number;
  gradebook_grading_period_id: number;
  title: string;
  weight: number;
  gradebook_grading_period?: GradeBookGradingPeriod;
  gradebook_item_details?: GradeBookItemDetail[];
}
