/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GradeBookItem } from './gradeBookItem';

export interface GradeBookItemDetail {
  readonly id?: number;
  gradebook_item_id: number;
  title: string;
  min_score: number;
  max_score: number;
  weight: number;
  gradebook_item?: GradeBookItem;
}
