/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GradeBookItemDetail } from './gradeBookItemDetail';
import type { Enrollment } from './enrollment';

export interface GradeBookScore {
  readonly id?: number;
  gradebook_item_detail_id: number;
  enrollment_id: number;
  score: number;
  readonly created_at?: string;
  readonly updated_at?: string;
  gradebook_item_detail?: GradeBookItemDetail;
  enrollment?: Enrollment;
}
