/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { Section } from './section';
import type { AcademicProgram } from './academicProgram';
import type { GradeBookGradingPeriod } from './gradeBookGradingPeriod';

export interface GradeBook {
  readonly id?: number;
  /** @nullable */
  section_id?: number | null;
  /** @nullable */
  academic_program_id: number | null;
  is_template: boolean;
  title: string;
  fully_setup?: boolean;
  section?: Section;
  academic_program?: AcademicProgram;
  gradebook_grading_periods?: GradeBookGradingPeriod[];
}
