/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GradeBook } from './gradeBook';
import type { GradeBookItemDetail } from './gradeBookItemDetail';

export interface GradeBookItem {
  readonly id?: number;
  gradebook_id: number;
  title: string;
  weight: number;
  gradebook?: GradeBook;
  gradebook_item_details?: GradeBookItemDetail[];
}
