/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GradeBook } from './gradeBook';
import type { GradeBookItem } from './gradeBookItem';

export interface GradeBookGradingPeriod {
  readonly id?: number;
  gradebook_id: number;
  title: string;
  weight: number;
  gradebook?: GradeBook;
  gradebook_items?: GradeBookItem[];
}
