/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

/**
 * Standard internal server error response
 */
export interface InternalServerErrorResponse {
  status?: string;
  message?: string;
}
