/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export interface KeyValuePair {
  label: string;
  value: string;
  /** @nullable */
  parent_value?: string | null;
}
