/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

/**
 * Pagination and metadata for the response
 */
export interface MetaData {
  current_page: number;
  last_page: number;
  per_page: number;
  total: number;
}
