/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export interface MultipleCurriculumDetail {
  curriculum_id: number;
  year_order: number;
  term_order: number;
  term_alias: string;
  is_include_gwa: boolean;
  courses: number[];
}
