/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { Campus } from './campus';

export interface Office {
  readonly id?: number;
  name: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  website?: string | null;
  readonly created_at?: string;
  readonly updated_at?: string;
  campus_id?: number;
  campus?: Campus;
}
