/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedGradeBookScore } from './paginatedGradeBookScore';

export interface PaginatedGradeBookScoreResponse200 {
  success?: boolean;
  data?: PaginatedGradeBookScore;
}
