/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedSectionTeacher } from './paginatedSectionTeacher';

export interface PaginatedSectionTeacherResponse200 {
  success?: boolean;
  data?: PaginatedSectionTeacher;
}
