/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedUniversityAdmissionSchedule } from './paginatedUniversityAdmissionSchedule';

export interface PaginatedUniversityAdmissionScheduleResponse200 {
  success?: boolean;
  data?: PaginatedUniversityAdmissionSchedule;
}
