/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { Designition } from './designition';
import type { User } from './user';
import type { PaginatedDesignitionDesignitionable } from './paginatedDesignitionDesignitionable';

export interface PaginatedDesignition {
  data?: Designition[];
  current_page?: number;
  last_page?: number;
  per_page?: number;
  total?: number;
  /** @nullable */
  from?: number | null;
  /** @nullable */
  to?: number | null;
  user?: User;
  designitionable?: PaginatedDesignitionDesignitionable;
}
