/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GradeBookItemDetail } from './gradeBookItemDetail';

export interface PaginatedGradeBookItemDetail {
  data?: GradeBookItemDetail[];
  current_page?: number;
  last_page?: number;
  per_page?: number;
  total?: number;
  /** @nullable */
  from?: number | null;
  /** @nullable */
  to?: number | null;
}
