/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedAdmissionScore } from './paginatedAdmissionScore';

export interface PaginatedAdmissionScoreResponse200 {
  success?: boolean;
  data?: PaginatedAdmissionScore;
}
