/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedEnrollment } from './paginatedEnrollment';

export interface PaginatedEnrollmentResponse200 {
  success?: boolean;
  data?: PaginatedEnrollment;
}
