/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedCurriculumDetail } from './paginatedCurriculumDetail';
import type { CurriculumDetail } from './curriculumDetail';

export type PaginatedCurriculumDetailResponse200Data = PaginatedCurriculumDetail | CurriculumDetail[];
