/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedAcademicProgramCriteria } from './paginatedAcademicProgramCriteria';

export interface PaginatedAcademicProgramCriteriaResponse200 {
  success?: boolean;
  data?: PaginatedAcademicProgramCriteria;
}
