/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { RequirementRequirementType } from './requirementRequirementType';

export interface Requirement {
  readonly id?: number;
  requirement_name: string;
  /** @nullable */
  description?: string | null;
  requirement_type: RequirementRequirementType;
  is_mandatory: boolean;
  is_active: boolean;
  readonly created_at?: string;
  readonly updated_at?: string;
}
