/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type RequirementTypeEnum = typeof RequirementTypeEnum[keyof typeof RequirementTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequirementTypeEnum = {
  admission: 'admission',
  graduation: 'graduation',
  enrollment: 'enrollment',
  scholarship: 'scholarship',
  transfer: 'transfer',
  general: 'general',
} as const;
