/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { Building } from './building';

export interface Room {
  id?: number;
  name: string;
  short_name: string;
  building_id: number;
  floor: number;
  room_code: string;
  is_lab: boolean;
  room_capacity: number;
  created_at?: string;
  updated_at?: string;
  building?: Building;
}
