/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { Section } from './section';
import type { Room } from './room';

export interface ScheduleAssignment {
  readonly id?: number;
  section_id: number;
  room_id: number;
  day_schedule: string;
  start_time: string;
  end_time: string;
  readonly created_at?: string;
  readonly updated_at?: string;
  section?: Section;
  room?: Room;
}
