/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export interface SchoolYear {
  readonly id?: number;
  school_year_code: string;
  name: string;
  start_date: string;
  end_date: string;
  is_active: boolean;
  readonly created_at?: string;
  readonly updated_at?: string;
  readonly is_locked?: boolean;
  readonly is_current?: boolean;
}
