/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export interface Section {
  readonly id?: number;
  curriculum_detail_id: number;
  school_year_id: number;
  section_ref: string;
  section_name: string;
  min_students: number;
  max_students: number;
  is_posted: boolean;
}
