/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { Section } from './section';
import type { User } from './user';

export interface SectionTeacher {
  id?: number;
  section_id: number;
  user_id: number;
  section?: Section;
  user?: User;
}
