/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type SubmitAdmissionApplicationFormBody = {
  'user_id[]'?: number[];
  'admission_schedule_id[]'?: number[];
  'admission_criteria_id[]'?: number[];
  'file[]'?: Blob[];
};
