/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type SubmitApplicationFormBodyItem = {
  user_id: number;
  university_admission_id: number;
  criteria_id: number;
  file: Blob;
};
