/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

/**
 * The data returned by the API
 * @nullable
 */
export type SuccessResponseData = { [key: string]: unknown } | null;
