/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { SuccessResponseData } from './successResponseData';

/**
 * Standard success response
 */
export interface SuccessResponse {
  status?: string;
  /**
   * The data returned by the API
   * @nullable
   */
  data?: SuccessResponseData;
}
