/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export interface SyncGradingPeriodGrade {
  /** @nullable */
  id?: number | null;
  gradebook_grading_period_id?: number;
  enrollment_id?: number;
  grade?: number;
  recommended_grade?: number;
  is_overridden?: boolean;
  is_posted?: boolean;
}
