/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export interface SyncGradeBookScore {
  /** @nullable */
  id?: number | null;
  gradebook_item_detail_id?: number;
  enrollment_id?: number;
  score?: number;
}
