/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { Room } from './room';

export interface TestingCenter {
  id?: number;
  room_id: number;
  code: string;
  created_at?: string;
  updated_at?: string;
  room?: Room;
}
