/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export interface UniversityAdmissionApplicationForm {
  university_admission_id: number;
  user_id: number;
  file: Blob;
  university_admission_criteria_id: number;
}
