/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { UniversityAdmission } from './universityAdmission';
import type { TestingCenter } from './testingCenter';

export interface UniversityAdmissionSchedule {
  id?: number;
  university_admission_id: number;
  testing_center_id: number;
  start_date: string;
  end_date: string;
  created_at?: string;
  updated_at?: string;
  university_admission?: UniversityAdmission;
  testing_center?: TestingCenter;
}
