/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export interface UniversityAdmissionApplication {
  readonly id?: number;
  university_admission_id: number;
  /** @nullable */
  university_admission_schedule_id?: number | null;
  user_id: number;
  /** @nullable */
  is_passed?: boolean | null;
  /** @nullable */
  score?: number | null;
  remark: string;
  year?: number;
  pool_no?: number;
  readonly created_at?: string;
  readonly updated_at?: string;
}
