/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type UniversityAdmissionApplicationNextStep = typeof UniversityAdmissionApplicationNextStep[keyof typeof UniversityAdmissionApplicationNextStep];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UniversityAdmissionApplicationNextStep = {
  not_eligible: 'not_eligible',
  schedule_selection: 'schedule_selection',
  take_exam: 'take_exam',
  apply_to_program: 'apply_to_program',
  locked: 'locked',
} as const;
