/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { UniversityAdmission } from './universityAdmission';
import type { Requirement } from './requirement';

export interface UniversityAdmissionCriteria {
  readonly id?: number;
  university_admission_id: number;
  requirement_id: number;
  title: string;
  /** @nullable */
  description?: string | null;
  max_score: number;
  min_score: number;
  weight: number;
  is_active: boolean;
  file_suffix: string;
  readonly created_at?: string;
  readonly updated_at?: string;
  university_admission?: UniversityAdmission;
  requirement?: Requirement;
}
