/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { UniversityAdmissionApplication } from './universityAdmissionApplication';
import type { UniversityAdmissionCriteria } from './universityAdmissionCriteria';
import type { UniversityAdmissionApplicationCriteriaSubmissionFilesItem } from './universityAdmissionApplicationCriteriaSubmissionFilesItem';

export interface UniversityAdmissionApplicationCriteriaSubmission {
  id?: number;
  university_admission_application_id: number;
  university_admission_criteria_id: number;
  created_at?: string;
  updated_at?: string;
  university_admission_application?: UniversityAdmissionApplication;
  university_admission_criteria?: UniversityAdmissionCriteria;
  files?: UniversityAdmissionApplicationCriteriaSubmissionFilesItem[];
}
