/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { UniversityAdmissionApplicationLatestStatus } from './universityAdmissionApplicationLatestStatus';
import type { User } from './user';
import type { UniversityAdmission } from './universityAdmission';
import type { UniversityAdmissionApplicationUniversityAdmissionSchedule } from './universityAdmissionApplicationUniversityAdmissionSchedule';
import type { UniversityAdmissionApplicationCriteriaSubmission } from './universityAdmissionApplicationCriteriaSubmission';
import type { UniversityAdmissionApplicationLog } from './universityAdmissionApplicationLog';

export interface UniversityAdmissionApplication {
  readonly id?: number;
  university_admission_id: number;
  /** @nullable */
  university_admission_schedule_id?: number | null;
  user_id: number;
  /** @nullable */
  is_passed?: boolean | null;
  /** @nullable */
  score?: number | null;
  remark: string;
  year?: number;
  pool_no?: number;
  readonly created_at?: string;
  readonly updated_at?: string;
  readonly temporary_id?: string;
  readonly latest_status?: UniversityAdmissionApplicationLatestStatus;
  readonly latest_status_label?: string;
  user?: User;
  university_admission?: UniversityAdmission;
  /** @nullable */
  university_admission_schedule?: UniversityAdmissionApplicationUniversityAdmissionSchedule;
  university_admission_criteria_submissions?: UniversityAdmissionApplicationCriteriaSubmission[];
  logs?: UniversityAdmissionApplicationLog[];
}
