/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { UniversityAdmissionApplicationCriteriaSubmissionFilesItemManipulations } from './universityAdmissionApplicationCriteriaSubmissionFilesItemManipulations';
import type { UniversityAdmissionApplicationCriteriaSubmissionFilesItemCustomProperties } from './universityAdmissionApplicationCriteriaSubmissionFilesItemCustomProperties';
import type { UniversityAdmissionApplicationCriteriaSubmissionFilesItemGeneratedConversions } from './universityAdmissionApplicationCriteriaSubmissionFilesItemGeneratedConversions';
import type { UniversityAdmissionApplicationCriteriaSubmissionFilesItemResponsiveImages } from './universityAdmissionApplicationCriteriaSubmissionFilesItemResponsiveImages';

export type UniversityAdmissionApplicationCriteriaSubmissionFilesItem = {
  id?: number;
  model_type?: string;
  model_id?: number;
  /** @nullable */
  uuid?: string | null;
  collection_name?: string;
  name?: string;
  file_name?: string;
  /** @nullable */
  mime_type?: string | null;
  disk?: string;
  /** @nullable */
  conversions_disk?: string | null;
  size?: number;
  manipulations?: UniversityAdmissionApplicationCriteriaSubmissionFilesItemManipulations;
  custom_properties?: UniversityAdmissionApplicationCriteriaSubmissionFilesItemCustomProperties;
  generated_conversions?: UniversityAdmissionApplicationCriteriaSubmissionFilesItemGeneratedConversions;
  responsive_images?: UniversityAdmissionApplicationCriteriaSubmissionFilesItemResponsiveImages;
  /** @nullable */
  order_column?: number | null;
  /** @nullable */
  created_at?: string | null;
  /** @nullable */
  updated_at?: string | null;
};
