/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { SchoolYear } from './schoolYear';
import type { UniversityAdmissionCriteria } from './universityAdmissionCriteria';
import type { AdmissionSchedule } from './admissionSchedule';

export interface UniversityAdmission {
  readonly id?: number;
  school_year_id: number;
  title?: string;
  open_date: string;
  close_date: string;
  is_open_override: boolean;
  readonly is_ongoing?: boolean;
  school_year?: SchoolYear;
  university_admission_criterias?: UniversityAdmissionCriteria[];
  admission_schedules?: AdmissionSchedule[];
}
