/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type UpdateUniversityAdmissionApplicationCriteriaSubmissionScoresRequestScoresItem = {
  university_admission_criteria_submission_id: number;
  /** @nullable */
  score?: number | null;
};
