/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { FinalGrade } from './finalGrade';

export interface UpdateFinalGradeResponse200 {
  success?: boolean;
  data?: FinalGrade;
}
