/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { UniversityAdmissionApplicationCriteriaSubmission } from './universityAdmissionApplicationCriteriaSubmission';

export interface UpdateUniversityAdmissionApplicationCriteriaSubmissionScoresResponse200 {
  success?: boolean;
  data?: UniversityAdmissionApplicationCriteriaSubmission[];
}
