/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { GradingPeriodGrade } from './gradingPeriodGrade';

export interface UpdateGradingPeriodGradeResponse200 {
  success?: boolean;
  data?: GradingPeriodGrade;
}
