/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { UserRoleEnum } from './userRoleEnum';

export interface User {
  readonly id?: number;
  name: string;
  email: string;
  password: string;
  role?: UserRoleEnum;
  /** @nullable */
  email_verified_at?: string | null;
  created_at?: string;
  updated_at?: string;
  readonly roles?: readonly string[];
  readonly profile_weight?: number;
}
