/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type UserRoleEnum = typeof UserRoleEnum[keyof typeof UserRoleEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRoleEnum = {
  admin: 'admin',
  program_chair: 'program_chair',
  college_dean: 'college_dean',
  specialization_chair: 'specialization_chair',
  campus_scheduler: 'campus_scheduler',
  campus_registrar: 'campus_registrar',
  student: 'student',
  faculty: 'faculty',
  guest: 'guest',
} as const;
