/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */
import type { UserRole } from './userRole';

export interface User {
  readonly id?: number;
  name: string;
  email: string;
  password: string;
  readonly role?: UserRole;
  /** @nullable */
  email_verified_at?: string | null;
  created_at?: string;
  updated_at?: string;
  roles?: string[];
}
