/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenEdusync API
 * API documentation for the OpenEdusy application
 * OpenAPI spec version: 1.0.0
 */

export type WeeklyScheduleEnum = typeof WeeklyScheduleEnum[keyof typeof WeeklyScheduleEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WeeklyScheduleEnum = {
  Sunday: 'Sunday',
  Monday: 'Monday',
  Tuesday: 'Tuesday',
  Wednesday: 'Wednesday',
  Thursday: 'Thursday',
  Friday: 'Friday',
  Saturday: 'Saturday',
} as const;
