<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Course;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $courses = [
            // First Year - General Education & Foundation
            [
                'id' => 1,
                'course_code' => 'CS101',
                'course_title' => 'Introduction to Computer Science',
                'course_description' => 'A foundational course covering basic computer science concepts, problem-solving, and computational thinking.',
                'with_laboratory' => true,
                'is_specialize' => false,
                'lecture_units' => 2.0,
                'laboratory_units' => 1.0,
                'credit_units' => 3.0,
            ],
            [
                'id' => 2,
                'course_code' => 'PROG101',
                'course_title' => 'Computer Programming 1',
                'course_description' => 'Introduction to programming fundamentals using a high-level programming language. Covers variables, data types, control structures, and basic algorithms.',
                'with_laboratory' => true,
                'is_specialize' => false,
                'lecture_units' => 2.0,
                'laboratory_units' => 1.0,
                'credit_units' => 3.0,
            ],
            [
                'id' => 3,
                'course_code' => 'PROG102',
                'course_title' => 'Computer Programming 2',
                'course_description' => 'Advanced programming concepts including object-oriented programming, data structures, and algorithm design.',
                'with_laboratory' => true,
                'is_specialize' => false,
                'lecture_units' => 2.0,
                'laboratory_units' => 1.0,
                'credit_units' => 3.0,
            ],
            [
                'id' => 4,
                'course_code' => 'MATH101',
                'course_title' => 'Discrete Mathematics',
                'course_description' => 'Mathematical foundations for computer science including logic, sets, relations, functions, and graph theory.',
                'with_laboratory' => false,
                'is_specialize' => false,
                'lecture_units' => 3.0,
                'laboratory_units' => 0.0,
                'credit_units' => 3.0,
            ],
            
            // Second Year - Core CS/IT Courses
            [
                'id' => 5,
                'course_code' => 'DS201',
                'course_title' => 'Data Structures and Algorithms',
                'course_description' => 'Study of fundamental data structures and algorithms including arrays, linked lists, stacks, queues, trees, graphs, sorting, and searching.',
                'with_laboratory' => true,
                'is_specialize' => false,
                'lecture_units' => 2.0,
                'laboratory_units' => 1.0,
                'credit_units' => 3.0,
            ],
            [
                'id' => 6,
                'course_code' => 'DB201',
                'course_title' => 'Database Management Systems',
                'course_description' => 'Introduction to database concepts, relational database design, SQL, normalization, and database administration.',
                'with_laboratory' => true,
                'is_specialize' => false,
                'lecture_units' => 2.0,
                'laboratory_units' => 1.0,
                'credit_units' => 3.0,
            ],
            [
                'id' => 7,
                'course_code' => 'WEB201',
                'course_title' => 'Web Development',
                'course_description' => 'Fundamentals of web development including HTML, CSS, JavaScript, and responsive design principles.',
                'with_laboratory' => true,
                'is_specialize' => false,
                'lecture_units' => 2.0,
                'laboratory_units' => 1.0,
                'credit_units' => 3.0,
            ],
            [
                'id' => 8,
                'course_code' => 'OOP201',
                'course_title' => 'Object-Oriented Programming',
                'course_description' => 'Advanced study of object-oriented programming principles including inheritance, polymorphism, encapsulation, and design patterns.',
                'with_laboratory' => true,
                'is_specialize' => false,
                'lecture_units' => 2.0,
                'laboratory_units' => 1.0,
                'credit_units' => 3.0,
            ],
            [
                'id' => 9,
                'course_code' => 'NET201',
                'course_title' => 'Computer Networks',
                'course_description' => 'Introduction to computer networking concepts, protocols, network architecture, and network security.',
                'with_laboratory' => true,
                'is_specialize' => false,
                'lecture_units' => 2.0,
                'laboratory_units' => 1.0,
                'credit_units' => 3.0,
            ],
            
            // Third Year - Advanced Topics
            [
                'id' => 10,
                'course_code' => 'SE301',
                'course_title' => 'Software Engineering',
                'course_description' => 'Software development methodologies, project management, requirements analysis, design, testing, and maintenance.',
                'with_laboratory' => true,
                'is_specialize' => false,
                'lecture_units' => 2.0,
                'laboratory_units' => 1.0,
                'credit_units' => 3.0,
            ],
            [
                'id' => 11,
                'course_code' => 'OS301',
                'course_title' => 'Operating Systems',
                'course_description' => 'Study of operating system concepts including process management, memory management, file systems, and security.',
                'with_laboratory' => true,
                'is_specialize' => false,
                'lecture_units' => 2.0,
                'laboratory_units' => 1.0,
                'credit_units' => 3.0,
            ],
            [
                'id' => 12,
                'course_code' => 'AI301',
                'course_title' => 'Artificial Intelligence',
                'course_description' => 'Introduction to artificial intelligence concepts including search algorithms, knowledge representation, machine learning, and expert systems.',
                'with_laboratory' => true,
                'is_specialize' => true,
                'lecture_units' => 2.0,
                'laboratory_units' => 1.0,
                'credit_units' => 3.0,
            ],
            [
                'id' => 13,
                'course_code' => 'ML301',
                'course_title' => 'Machine Learning',
                'course_description' => 'Fundamentals of machine learning including supervised and unsupervised learning, neural networks, and deep learning.',
                'with_laboratory' => true,
                'is_specialize' => true,
                'lecture_units' => 2.0,
                'laboratory_units' => 1.0,
                'credit_units' => 3.0,
            ],
            [
                'id' => 14,
                'course_code' => 'MOBILE301',
                'course_title' => 'Mobile Application Development',
                'course_description' => 'Development of mobile applications for iOS and Android platforms using modern frameworks and tools.',
                'with_laboratory' => true,
                'is_specialize' => true,
                'lecture_units' => 2.0,
                'laboratory_units' => 1.0,
                'credit_units' => 3.0,
            ],
            [
                'id' => 15,
                'course_code' => 'CYBER301',
                'course_title' => 'Cybersecurity Fundamentals',
                'course_description' => 'Introduction to cybersecurity concepts, threats, vulnerabilities, cryptography, and security best practices.',
                'with_laboratory' => true,
                'is_specialize' => true,
                'lecture_units' => 2.0,
                'laboratory_units' => 1.0,
                'credit_units' => 3.0,
            ],
            
            // Fourth Year - Specialization & Capstone
            [
                'id' => 16,
                'course_code' => 'CLOUD401',
                'course_title' => 'Cloud Computing',
                'course_description' => 'Study of cloud computing architectures, services, deployment models, and cloud-based application development.',
                'with_laboratory' => true,
                'is_specialize' => true,
                'lecture_units' => 2.0,
                'laboratory_units' => 1.0,
                'credit_units' => 3.0,
            ],
            [
                'id' => 17,
                'course_code' => 'BIGDATA401',
                'course_title' => 'Big Data Analytics',
                'course_description' => 'Introduction to big data technologies, data mining, analytics tools, and distributed computing frameworks.',
                'with_laboratory' => true,
                'is_specialize' => true,
                'lecture_units' => 2.0,
                'laboratory_units' => 1.0,
                'credit_units' => 3.0,
            ],
            [
                'id' => 18,
                'course_code' => 'IOT401',
                'course_title' => 'Internet of Things',
                'course_description' => 'Study of IoT architectures, sensors, embedded systems, and IoT application development.',
                'with_laboratory' => true,
                'is_specialize' => true,
                'lecture_units' => 2.0,
                'laboratory_units' => 1.0,
                'credit_units' => 3.0,
            ],
            [
                'id' => 19,
                'course_code' => 'CAPSTONE401',
                'course_title' => 'Capstone Project 1',
                'course_description' => 'First part of the capstone project where students design and plan their final project.',
                'with_laboratory' => true,
                'is_specialize' => false,
                'lecture_units' => 1.0,
                'laboratory_units' => 2.0,
                'credit_units' => 3.0,
            ],
            [
                'id' => 20,
                'course_code' => 'CAPSTONE402',
                'course_title' => 'Capstone Project 2',
                'course_description' => 'Second part of the capstone project where students implement, test, and present their final project.',
                'with_laboratory' => true,
                'is_specialize' => false,
                'lecture_units' => 1.0,
                'laboratory_units' => 2.0,
                'credit_units' => 3.0,
            ],
            
            // Additional IT/CS Courses
            [
                'id' => 21,
                'course_code' => 'HCI301',
                'course_title' => 'Human-Computer Interaction',
                'course_description' => 'Study of user interface design, usability principles, user experience, and interaction design.',
                'with_laboratory' => true,
                'is_specialize' => true,
                'lecture_units' => 2.0,
                'laboratory_units' => 1.0,
                'credit_units' => 3.0,
            ],
            [
                'id' => 22,
                'course_code' => 'GAME301',
                'course_title' => 'Game Development',
                'course_description' => 'Introduction to game design and development including game engines, graphics, physics, and gameplay mechanics.',
                'with_laboratory' => true,
                'is_specialize' => true,
                'lecture_units' => 2.0,
                'laboratory_units' => 1.0,
                'credit_units' => 3.0,
            ],
            [
                'id' => 23,
                'course_code' => 'BLOCKCHAIN401',
                'course_title' => 'Blockchain Technology',
                'course_description' => 'Study of blockchain fundamentals, cryptocurrencies, smart contracts, and decentralized applications.',
                'with_laboratory' => true,
                'is_specialize' => true,
                'lecture_units' => 2.0,
                'laboratory_units' => 1.0,
                'credit_units' => 3.0,
            ],
            [
                'id' => 24,
                'course_code' => 'DEVOPS401',
                'course_title' => 'DevOps and Continuous Integration',
                'course_description' => 'Introduction to DevOps practices, CI/CD pipelines, containerization, and infrastructure automation.',
                'with_laboratory' => true,
                'is_specialize' => true,
                'lecture_units' => 2.0,
                'laboratory_units' => 1.0,
                'credit_units' => 3.0,
            ],
            [
                'id' => 25,
                'course_code' => 'ETHICS201',
                'course_title' => 'IT Ethics and Professional Practice',
                'course_description' => 'Study of ethical issues in computing, professional responsibilities, privacy, security, and social impact of technology.',
                'with_laboratory' => false,
                'is_specialize' => false,
                'lecture_units' => 3.0,
                'laboratory_units' => 0.0,
                'credit_units' => 3.0,
            ],
        ];

        foreach ($courses as $course) {
            Course::create($course);
        }
    }
}
